#Сколько тиков длится захват региона
capture_ticks: 200
#Интервал обновления состояния захвата
#Раз в столько тиков проверяется, находятся ли захватывающие игроки в регионах, которые захватывают,
#и раз в столько тиков выплачивается доля из региона
capture_upd_ticks: 40
#Раз в столько тиков игроки награждаются за захваченные регионы
reward_period: 100
#Название предмета, который выплачивается игроку
reward_item: iron
#Количество предмета, который выплачивается
reward_amount: 10